FROM local/centos7
RUN yum -y update
RUN yum -y install epel-release python36 python36-devel gcc
ENV FLASK_APP index.py
ENV PERMANENT_SESSION_LIFETIME 7200
ENV AUTHLIB_INSECURE_TRANSPORT 1
ENV LC_ALL=en_US.utf-8
ENV LANG=en_US.utf-8
ADD . /var/www/html
WORKDIR /var/www/html
RUN pip3 install --upgrade pip setuptools==45.2.0
RUN pip3 install -r requirements.txt

CMD ["/var/www/html/init.sh"]
