"""20210522
create table:
- trade_records
- stock_data
- stock_chip
- users
- stock_basic_info
- three_days_predict
- five_days_predict


Revision ID: 48c90b53b3b3
Revises: 
Create Date: 2021-05-22 12:32:56.540822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c90b53b3b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_symbol', sa.String(length=20), nullable=False, comment='股票代號'),
    sa.Column('stock_name', sa.String(length=60), nullable=False, comment='股票名稱'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False, comment='使用者名稱'),
    sa.Column('email', sa.String(length=120), nullable=False, comment='使用者e-mail'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('five_days_predict',
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('future_first_day', sa.Float(), nullable=False, comment='預測第一天價格'),
    sa.Column('future_second_day', sa.Float(), nullable=False, comment='預測第二天價格'),
    sa.Column('future_third_day', sa.Float(), nullable=False, comment='預測第三天價格'),
    sa.Column('future_forth_day', sa.Float(), nullable=False, comment='預測第四天價格'),
    sa.Column('future_fifth_day', sa.Float(), nullable=False, comment='預測地五天價格'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.PrimaryKeyConstraint('stock_basic_info_id')
    )
    op.create_table('stock_chip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('net_buy_volume', sa.Integer(), nullable=False, comment='三大法人買超(張)'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='交易日其'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('opening_price', sa.Float(), nullable=False, comment='開盤價'),
    sa.Column('closing_price', sa.Float(), nullable=False, comment='收盤價'),
    sa.Column('highest_price', sa.Float(), nullable=False, comment='最高價'),
    sa.Column('lowest_price', sa.Float(), nullable=False, comment='最低價'),
    sa.Column('volume', sa.Integer(), nullable=False, comment='交易量'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='交易日期'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('three_days_predict',
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('three_days_increase_one_percent', sa.Float(), nullable=False, comment='漲幅1%機率'),
    sa.Column('three_days_increase_three_percent', sa.Float(), nullable=False, comment='漲幅3%機率'),
    sa.Column('three_days_no_change', sa.Float(), nullable=False, comment='無變動機率'),
    sa.Column('three_days_decrease_one_percent', sa.Float(), nullable=False, comment='跌幅1%機率'),
    sa.Column('three_days_decrease_three_percent', sa.Float(), nullable=False, comment='跌幅3%機率'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.PrimaryKeyConstraint('stock_basic_info_id')
    )
    op.create_table('trade_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_basic_info_id', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False, comment='交易量(股數)'),
    sa.Column('price', sa.Float(), nullable=False, comment='交易價格'),
    sa.Column('cost', sa.Float(), nullable=False, comment='交易成本'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='創造時間'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='修改時間'),
    sa.ForeignKeyConstraint(['stock_basic_info_id'], ['stock_basic_info.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_records')
    op.drop_table('three_days_predict')
    op.drop_table('stock_data')
    op.drop_table('stock_chip')
    op.drop_table('five_days_predict')
    op.drop_table('users')
    op.drop_table('stock_basic_info')
    # ### end Alembic commands ###
