# install centos & python
FROM docker.io/centos/python-36-centos7
# workdir
WORKDIR /var/www/html/
# Install python modules
RUN pip3 install --upgrade pip setuptools==45.2.0
# python path in /var/www/html
ENV PYTHONPATH "${PYTHONPATH}:/var/www/html"
# Run shell script
CMD ["/var/www/html/crawler/init.sh"]

