FROM local/centos7
RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -
RUN yum install nodejs -y
RUN npm install -g @vue/cli @vue/cli-service-global
RUN npm install -g @vue/cli-init
RUN npm install webpack-dev-server@2.9.1
RUN npm install --save-dev webpack webpack-cli webpack-dev-server
RUN npm install --save-dev webpack webpack-cli webpack-dev-server webpack-merge
WORKDIR /var/www/html
CMD ["/var/www/html/init.sh"]

